- gestao/urls.py
- gestao/views.py
- manage.py
- snc/templates/gestao/base_gestao.html
- snc/templates/gestao/planotrabalho/acompanhar_conselho.html
- snc/templates/gestao/planotrabalho/acompanhar_fundo.html
- snc/templates/gestao/planotrabalho/acompanhar_orgao.html
- snc/templates/gestao/planotrabalho/acompanhar_plano.html
- snc/templates/gestao/planotrabalho/acompanhar_sistema.html
Equipe de negócio ainda usa a feature antiga como "fila de pendências"
Retornando essa feature para prod até melhorarmos a funcionalidade de análise documental
> restaurando Feature de análise antiga

- api/urls.py
- requirements.txt
- snc/config/settings/common.py
- snc/hosts.py
- snc/urls.py
- Host da api: api.
- Host padrão: www.
> [ADD] Adiciona django hosts para configuração de hosts

- api/serializers.py
> [UPDATE] Campo endereco eletronico posicionado dentro do serializer EnteFederado

- api/static/swagger/swagger.json
Atualização da documentação da API (Swagger) segundo as novas opções de pesquisa da mesma.
> [UPDATE] Atualização do arquivo swagger.json

- api/serializers.py
Cria recurso embedded no endpoint /acoesplanotrabalho com link para o sistema de cultura relacionado.
> [UPDATE] Adiciona link para sistema de cultura no endpoint acoesplanotrabalho

- env.tmpl
- snc/settings.py
> [FIX] Corrige ROOT_DIR e configuração do raven em settings.py

- gestao/views.py
- snc/templates/gestao/adesao/acompanhar.html
- snc/templates/gestao/base_gestao.html
Adequação da tela de gestão para que todos os entes federados presentes em qualquer situação processual possam aparecer na tela principal.
> Fix issue54

- snc/settings.py
Altera o parametro ROOT_DIR para buscar a raiz da aplicação.
> [FIX] Altera o parametro ROOT_DIR

- adesao/tests.py
- snc/settings.py
- Corrige caminho para templates e estáticos nas configurações da aplicação
- Testa envio de email e template da funcionalidade password_reset
- Corrige domínio padrão utilizado pelo django-sites
> Fix password reset

- .gitignore
- adesao/migrations/0001_initial.py
- planotrabalho/migrations/0001_initial.py
- Adiciona no repositório as migrations relativas aos estados atuais
das models
> [ADD] Versiona migrações das models

- api/filters.py
- api/pagination.py
- api/serializers.py
- api/tests.py
- api/urls.py
- api/views.py
Trata do retorno da situação dos conselheiros de um ente federado. Refatora os testes criando fixtures reusáveis, além de remover código inútil e aplicar folha de estilo para os demais módulos do app API.
> Issue 137 Trata retorno da situação dos conselheiros

- api/metadata.py
- api/tests.py
- api/views.py
Implementa retorno para requisição do tipo OPTIONS.
- No endpoint ```sistemadeculturalocal/```:
- Retorna lista com os valores disponíveis dos fields referentes a situação da adesão, situação do conselheiro e segmento do conselheiro.
- No endpoint ```acoesplanotrabalho/```:
- Retorna lista com os valores disponíveis do field referente a situação dos arquivos do plano de trabalho.
> Implementa resposta para requisição do tipo OPTIONS

- planotrabalho/migrations/0004_migra_situacao_20180418_0949.py
Cria migração para copiar a situação dos componente dos antigos fields para o novo field referente a situação.
> Cria migração para atualizar situação dos componentes

- gestao/tests/test_views.py
- gestao/views.py
- snc/templates/gestao/diligencia/diligencia.html
Corrige criação para diligência geral para planos de trabalho que não possuem algum dos componentes
> Corrige criação de diligência geral

- snc/static/AlterarSenha.html
- snc/static/ElaboracaodoPlanodeCultura.html
- snc/static/EstruturacaoDosComponentes.html
- snc/static/EstruturacaoDosComponentes2-2.html
- snc/static/EstruturacaoDosComponentes2-3.html
- snc/static/Federado.html
- snc/static/InstitucionalizacaodoSistema.html
- snc/static/Interlocutor.html
- snc/static/PlanoDeTrabalho.html
- snc/static/Responsavel.html
- snc/static/Segunda.html
- snc/static/index.html
- snc/templates/base.html
- snc/templates/consultar/detalhar.html
Atualização do ano no rodapé da página conforme issue #134
> [UPDATE] Alterando ano no rodapé do sistema

- gestao/forms.py
Altera o campo utilizado referente a situação ao inicializar os componentes do Plano de trabalho para os novo campo utilizado para armazenar a situação dos componentes.
> Altera campo da situação no form AlterarSitucao

- snc/templates/conclusao_cadastro.email
- snc/templates/conclusao_cadastro.html
Atualiza o texto da home page, após cadastros, conforme solicitado na issue #164
> [UPDATE] Atualizando texto da home page

- snc/templates/home.html
Substitui o texto da home page de adesão conforme issue #100
> [UPDATE] Atualizando texto da home de adesao

- snc/templates/dados_municipio.html
- snc/templates/home.html
Atualiza texto da home page conforme issue #198
> [UPDATE] Atualiza texto da home page

- api/filters.py
- api/serializers.py
- api/tests.py
Adiciona nome da UF no retorno da API e permite a busca pelo nome da UF, conforme issue #196
> Retorna nome da UF na API

- adesao/models.py
- adesao/tests/test_models.py
- gestao/forms.py
- gestao/models.py
- gestao/tests/test_forms.py
- gestao/tests/test_views.py
- gestao/urls.py
- gestao/views.py
- snc/templates/gestao/adesao/acompanhar.html
- snc/templates/gestao/detalhe_municipio.html
Na tela de detalhe de um ente federado na área de gestão existiam dois formulários, um referente a o estado da adesão, outro referente ao número do processo do SEI, os dois formulários foram unificados em um único.
> Unifica form que trata do estado da adesão e do número processo do SEI

- conftest.py
- planotrabalho/forms.py
- planotrabalho/tests.py
- planotrabalho/tests/test_views.py
- planotrabalho/views.py
Corrige upload dos arquivos dos diferentes componentes, o erro ocorria pela falta da relação entre o componente e o plano de trabalho do ente federado no momento de salvar o objeto relativo ao componente.
> Corrige upload de arquivos dos componentes

- snc/templates/gestao/detalhe_municipio.html
Mostra também o email do usuário na tabela de histórico de cadastradores
> Adiciona email ao histórico de cadastradores

- snc/static/css/style.css
- snc/templates/gestao/adesao/acompanhar.html
- snc/templates/planotrabalho/cadastrar_fundo.html
- snc/templates/prefeitura/alterar_estado.html
- snc/templates/prefeitura/alterar_municipio.html
- snc/templates/prefeitura/formulario_estado.html
- snc/templates/prefeitura/formulario_municipio.html
- snc/templates/responsavel/cadastrar_responsavel.html
- snc/templates/secretario/cadastrar_secretario.html
- snc/templates/usuario/cadastrar_usuario.html
Coloca a classe has-error em campos com erros para tornar mensagens mais chamativas, conforme issue #228
> Issue 228 mensagens de erro

- api/tests/test_api.py
- api/views.py
Adiciona contagem de número de municípios, número de estados, número de municípios aderidos e número de estados aderidos ao retorno da API
> Issue 207 count

- gestao/tests/test_views.py
- gestao/views.py
Ordena os municípios na tela inicial de gestão conforme regras da issue #217
> Issue 217 ordenacao gestao

- snc/templates/planotrabalho/cadastrar_conselho.html
- snc/templates/planotrabalho/cadastrar_fundo.html
- snc/templates/planotrabalho/cadastrar_orgao.html
- snc/templates/planotrabalho/cadastrar_plano.html
- snc/templates/planotrabalho/cadastrar_sistema.html
Labals da Data de Publicação dos componentes conselho, fundo, orgão, plano e sistema de Cultura
> Issue 243 Alterar labels das Datas de Publicação

- snc/templates/conclusao_cadastro.email
- snc/templates/conclusao_cadastro.html
- snc/templates/fale_conosco.html
- snc/templates/home.html
Emails acordosnc@cultura.gov.br alterados para snc@cultura.gov.br
> Issue 244 Alterar o-email do snc

- gestao/forms.py
- gestao/views.py
Neste pull request foi feita a correção da pesquisa no select de municipios
> Issue 247 Select de municipio

- snc/templates/gestao/alterar_cadastrador.html
- snc/templates/gestao/detalhe_municipio.html
Nesse Pr foi feito:
* Issue 26:
- adicionando pop up de confirmação em "alteração do cadastrador" e "Alteração de Situação da Adesão"
> 26 adicionando pop up

- gestao/forms.py
- gestao/tests/test_forms.py
- gestao/tests/test_views.py
- gestao/views.py
- snc/templates/gestao/alterar_cadastrador.html
- snc/templates/gestao/detalhe_municipio.html
Nesse pr foi feito:
- validação do cpf (com verificação de cadastro)
- compatibilidade entre navegadores(Popup)
> 253 error cpf invalido

- snc/templates/planotrabalho/cadastrar_conselho.html
- snc/templates/planotrabalho/cadastrar_fundo.html
- snc/templates/planotrabalho/cadastrar_orgao.html
- snc/templates/planotrabalho/cadastrar_plano.html
- snc/templates/planotrabalho/cadastrar_sistema.html
Neste pull request foi colocado as labels definidas nos comentarios da issue #243
> mudando as labels de Data dos componentes

- gestao/views.py
- snc/settings.py
- snc/templates/gestao/acompanhar_prazo.html
- snc/templates/gestao/adesao/acompanhar.html
- snc/templates/gestao/alterar_cadastrador.html
- snc/templates/gestao/detalhe_municipio.html
- snc/templates/gestao/inserir_documentos/inserir_entefederado.html
- snc/templates/gestao/inserir_documentos/listar_conselhos.html
- snc/templates/gestao/inserir_documentos/listar_fundos.html
- snc/templates/gestao/inserir_documentos/listar_orgaos.html
- snc/templates/gestao/inserir_documentos/listar_planos.html
- snc/templates/gestao/inserir_documentos/listar_sistemas.html
- snc/templates/gestao/listar_usuarios.html
- snc/templates/messages.html
nesse PR foi feito:
- pop ups nas telas de alterar prazo e inserir documentos
- erro do cpf invalido
> issues 26 e 253 

- planotrabalho/forms.py
- snc/templates/gestao/alterar_cadastrador.html
- snc/templates/gestao/inserir_documentos/alterar_entefederado.html
- snc/templates/gestao/inserir_documentos/inserir_conselho.html
- snc/templates/gestao/inserir_documentos/inserir_fundo.html
- snc/templates/gestao/inserir_documentos/inserir_orgao.html
- snc/templates/gestao/inserir_documentos/inserir_plano.html
- snc/templates/gestao/inserir_documentos/inserir_sistema.html
- snc/templates/messages.html
Neste pull request foi feita a correção dos pop up na inserção de arquivos dos componentes e a troca do pop up padrão para uma modal
> 260 validacao arquivo pop up

- snc/templates/gestao/planotrabalho/acompanhar_conselho.html
- snc/templates/gestao/planotrabalho/acompanhar_fundo.html
- snc/templates/gestao/planotrabalho/acompanhar_orgao.html
- snc/templates/gestao/planotrabalho/acompanhar_plano.html
- snc/templates/gestao/planotrabalho/acompanhar_sistema.html
Neste pull request foi arrumado os likes e unlikes nas páginas de plano de trabalho
> 264 erro like

- snc/templates/gestao/base_gestao.html
Nesse Pr foi feito:
- retirada do terceiro nivel dos menus laterais esquerdos
> [FIX] tirando terceiro nivel dos menus laterais

- .gitignore
Removendo dump do repositório e adicionando extensões *.backup.bin e dump no gitignore
> [FIX] Removendo dump do repositório

- gestao/tests/test_views.py
- gestao/views.py
Neste pull request foi feito a busca por entes federados sem acentuação nas paginas de inserir documentos
> 262 adicionando acentuação ás paginas de documentos dos componentes

- snc/templates/gestao/inserir_documentos/listar_fundos.html
Nesse PR foi feito:
- Validação do cnpj do fundo para não aparecer None
> [FIX] adicionando validação de cnpj do fundo

- .checks.yml
Inicializa a configuração do LambaLint para verificações de estilo e segurança.
> Configura o LambdaLint

- adesao/models.py
- gestao/templates/detalhe_municipio.html
- gestao/tests/test_views.py
- gestao/urls.py
- gestao/views.py
Ajusta e exibição e atualização de informações e inicia os trabalhos em exibir os históricos de alteração de um sistema cultura.
> Ajustes de exibição do Histórico

- gestao/templates/diligencia.html
- gestao/tests/test_componentes.py
- gestao/views.py
Ajusta histórico das diligências gerais na tela de criação de uma diligência para o plano de trabalho
> Ajusta historico de diligencias do plano de trabalho

- adesao/models.py
- gestao/tests/test_views.py
- gestao/views.py
Corrige a ordenação dos objetos de SistemaCultura na tela inicial de gestão
> Corrige ordenacao

- gestao/forms.py
- gestao/templates/diligencia.html
- gestao/tests/test_forms.py
- gestao/tests/test_views.py
> Permite a criação de diligência sem texto p/ classificação concluída

- adesao/models.py
- adesao/tests/test_models.py
- gestao/templates/diligencia.html
- gestao/tests/test_views.py
- gestao/views.py
- snc/templates/gestao/adesao/acompanhar.html
Mostra tabela com o histórico de diligências dos componentes, na tela de criação de uma diligência geral
> Historico de diligência dos componentes

- gestao/forms.py
- gestao/tests/test_forms.py
- gestao/tests/test_views.py
- gestao/views.py
> Remove data de publicação quando estado não é publicado no dou

- adesao/models.py
- adesao/tests/test_models.py
- adesao/tests/test_views.py
- adesao/urls.py
- adesao/utils.py
- adesao/views.py
- gestao/forms.py
- gestao/templates/diligencia.html
- gestao/tests/test_forms.py
- gestao/tests/test_views.py
- gestao/views.py
- snc/templates/base.html
- snc/templates/consultar/consultar.html
- snc/templates/consultar/detalhar.html
- snc/templates/gestao/adesao/acompanhar.html
- snc/templates/index.html
- Refatora a tela de consulta de informações para usar SistemaCultura
- Refatora exportação ODS, XLS e CSV para usar SistemaCultura
- Separa a parte comum entre a exportação ODS e XLS na utils
- Mostra link da publicação no DOU na página de consultar informações
> Refatora consulta de informações para usar sc

- gestao/tests/test_views.py
- pytest.ini
Corrige testes de alteração de componentes
> Fix travis

- gestao/tests/test_views.py
- gestao/views.py
Co-authored-by: Polly <pollyana.medeirosk@gmail.com>
Co-authored-by: Luiz <luizfelipenet@hotmail.com>
Permitir a busca por municipios e estados sem acento. #319
> Permite busca sem acento

- gestao/tests/test_views.py
- gestao/views.py
Alteração da adição de prazo de um ano para dois
> Issue 322 alterar prazo

- adesao/tests/test_views.py
- adesao/urls.py
- adesao/utils.py
- adesao/views.py
- planotrabalho/tests/test_views.py
- planotrabalho/views.py
- snc/templates/base.html
- snc/templates/conclusao_cadastro.html
- snc/templates/dados_municipio.html
- snc/templates/dados_responsavel.html
- snc/templates/dados_secretario.html
- snc/templates/home.html
Alteração nos textos de boas vindas após cadastro após usuário cadastrado, no texto após cadastro de ente federado e após publicado no DOU.
> Issue 318 troca texto

- gestao/templates/diligencia.html
> Remove truncatechars do resumo da diligência

- snc/templates/gestao/base_gestao.html
> Troca nome do input da barra geral

- adesao/tests/test_views.py
- adesao/views.py
> Corrige view Detalhar para retornar conselheiros

- gestao/templates/cadastrador.html
> Adiciona mensagem de erros no form de alterar cadastrador

- gestao/templates/cadastrador.html
- gestao/tests/test_views.py
- gestao/views.py
> Altera forma como nome do ente federado é mostrado no dropdown de cadastro do ente

- adesao/tests/test_views.py
- adesao/urls.py
- adesao/utils.py
- adesao/views.py
- gestao/urls.py
- gestao/views.py
- snc/templates/base.html
- snc/templates/home.html
- snc/templates/termos/alterar_responsavel.html
- snc/templates/termos/minuta_acordo.html
- snc/templates/termos/solicitacao.html
- Generaliza as três views de geração de PDF em uma só (GerarPDF)
- Atualiza os templates para acessar SistemaCultura
Closes #358
> Corrige geração de PDFs para acessar infos do sistema cultura

- adesao/tests/test_views.py
- adesao/utils.py
- adesao/views.py
- snc/templates/dados_municipio.html
- Remove data de publicação da session
- Altera template que mostra os dados do município pra mostrar apenas link para publicação no DOU, sem a data
- Altera ordem dos ifs da home, colocando o que redireciona pra staff antes
> Remove data de publicação da session

- gestao/templates/detalhe_municipio.html
- gestao/tests/test_views.py
- gestao/views.py
Co-authored-by: Pollyana <pollyana.medeirosk@gmail.com>
- Corrige nome da variável no template
- Seleciona apenas cadastradores distintos
- Adiciona teste
Closes #378
> Corrige histórico dos cadastradores

- adesao/models.py
> Altera __str__ do ente para retornar 'Estado de nome_do_estado'

- gestao/tests/test_views.py
- snc/templates/gestao/planotrabalho/acompanhar_plano.html
- Corrige link para download do plano
- Remove links obsoletos
- Adiciona teste que checa links
Closes #387
> Corrige link para downlod do plano na tela de plano de trabalho

- snc/templates/gestao/planotrabalho/acompanhar_conselho.html
- snc/templates/gestao/planotrabalho/acompanhar_fundo_cultura.html
- snc/templates/gestao/planotrabalho/acompanhar_legislacao.html
- snc/templates/gestao/planotrabalho/acompanhar_orgao_gestor.html
- snc/templates/gestao/planotrabalho/acompanhar_plano.html
Closes #389 
Co-authored-by: Polly <pollyana.medeirosk@gmail.com>
> Corrigir acessos as paginas dos municipios pelo plano de trabalho

- apiv2/pagination.py
Ficando idêntico aquilo que os testes esperam
> Alterando o limite máximo de retorno por requisição

- gestao/forms.py
- gestao/tests/test_views.py
- gestao/urls.py
- gestao/views.py
- snc/templates/gestao/inserir_documentos/alterar_entefederado.html
- snc/templates/gestao/inserir_documentos/inserir_entefederado.html
- Altera forms e view para utilizar model Gestor
- Altera view AlterarDocumentosEnteFederado para acessar SistemaCultura
- Adiciona testes
> Corrige inserção de documentos do gestor para usar sistemacultura

- gestao/templates/detalhe_municipio.html
- snc/templates/gestao/planotrabalho/acompanhar_conselho.html
- snc/templates/gestao/planotrabalho/acompanhar_fundo_cultura.html
- snc/templates/gestao/planotrabalho/acompanhar_legislacao.html
- snc/templates/gestao/planotrabalho/acompanhar_orgao_gestor.html
- snc/templates/gestao/planotrabalho/acompanhar_plano.html
>  Trocar label do botão de criar diligência

- snc/templates/base.html
- snc/templates/index.html
>  Trocar link da opção 'Perguntas Frequentes

- snc/templates/gestao/planotrabalho/acompanhar_fundo_cultura.html
> Mostrar CNPJ do fundo de cultura na tela de plano do trabalho

- adesao/forms.py
- gestao/forms.py
Co-authored-by: Pollyana <pollyana.medeirosk@gmail.com>
> Aumenta max_upload_size

- apiv2/filters.py
- apiv2/tests/test_api.py
Co-authored-by: Pollyana <pollyana.medeirosk@gmail.com>
> Cria filtros para data dos componentes

- adesao/models.py
- adesao/utils.py
- adesao/views.py
> Issue adicionar colunas planilha

- adesao/models.py
- adesao/tests/test_models.py
- gestao/templates/detalhe_municipio.html
- gestao/tests/test_views.py
- gestao/views.py
Co-authored-by: Gabriel Avaloni <gabrielavaloni@gmail.com>
> Obtém histórico de cadastradores

- snc/templates/termos/minuta_acordo.html
> Alteracao no texto acordo minuta

- gestao/templates/detalhe_municipio.html
> Deixar os dois campos de e-mail visiveis mesmo que em branco

- snc/templates/planotrabalho/cadastrar_conselho.html
- snc/templates/planotrabalho/cadastrar_fundo.html
- snc/templates/planotrabalho/cadastrar_orgao.html
- snc/templates/planotrabalho/cadastrar_plano.html
- snc/templates/planotrabalho/cadastrar_sistema.html
- snc/templates/planotrabalho/plano_trabalho.html
> Atualizar os campos do quadros azuis

- snc/settings.py
> Issue #508

- snc/settings.py
> Closes #508

- adesao/utils.py
- snc/templates/consultar/detalhar.html
> Verifica se o ente possui sede e gestor na serialização

- adesao/utils.py
- adesao/views.py
Reverts culturagovbr/sistema-nacional-cultura#516
> Revert "Issue #502"

- adesao/utils.py
- adesao/views.py
Reverts culturagovbr/sistema-nacional-cultura#517
> Issue #502

- adesao/tests/test_forms.py
- gestao/templates/detalhe_municipio.html
- gestao/templates/diligencia.html
- gestao/tests/test_componentes.py
- gestao/tests/test_views.py
- gestao/views.py
Ainda estão quebrando:
- Os da ordenação da tela de entes
- Os da inserção de documentos
> Corrige os testes da refactor-layout

- snc/templates/planotrabalho/cadastrar_conselho.html
- snc/templates/planotrabalho/cadastrar_fundo.html
- snc/templates/planotrabalho/cadastrar_orgao.html
> Corrigir hífen no quadro azul de plano de trabalho

- adesao/templates/templated_email/conclusao_cadastro.email
- adesao/tests/test_views.py
- snc/templates/conclusao_cadastro.html
- snc/templates/home.html
> atualizando endereço

- gestao/tests/test_views.py
- planotrabalho/forms.py
- planotrabalho/models.py
- planotrabalho/views.py
Co-authored-by: Polly <pollyana.medeirosk@gmail.com>
Closes #556
> Colocar campo perfil do órgão gestor como obrigatório

- adesao/tests/test_models.py
- conftest.py
- Faz login na fixture utilizando uma requisição para que o middleware seja sempre chamado, de forma a atualizar a request no thread_locals
- Remove teste duplicado
> Corrige testes

- gestao/templates/detalhe_municipio.html
- gestao/tests/test_views.py
- gestao/urls.py
- gestao/views.py
- planotrabalho/forms.py
- planotrabalho/models.py
- planotrabalho/views.py
- snc/templates/gestao/inserir_documentos/inserir_conselho.html
- snc/templates/gestao/inserir_documentos/inserir_orgao_gestor.html
- snc/templates/planotrabalho/cadastrar_conselho.html
- snc/templates/planotrabalho/cadastrar_fundo.html
- snc/templates/planotrabalho/cadastrar_orgao.html
- snc/templates/planotrabalho/cadastrar_plano.html
- snc/templates/planotrabalho/cadastrar_sistema.html
- Coloca opção 'selecione' no dropdown de perfil do órgão gestor (#556)
- Remove 'else' do js que fazia com que aparecessem dois botões de salvar nas telas de alguns componentes (#651)
- Atualiza inserção do órgão gestor no módulo de ADM para o novo fluxo (#607)
- Corrige erros encontrados em homologação da issue #650
> Corrige upload de componentes no módulo de ADM

- snc/templates/fale_conosco.html
> Alterar endereço do "fale Conosco"

- adesao/tests/test_views.py
- adesao/utils.py
A data estava dando erro na serialização da session: https://sentry.cultura.gov.br/minc/snc-producao/issues/4830/
> Remove data de publicação da retificação da session

- planotrabalho/views.py
> [FIX] Correção de url de encaminhamento BACKEND #696

- planotrabalho/forms.py
Correção do validador do Formulário - Campo Obrigatório.
> [UPDATE] Campo Obrigatorio corrigido Segmento edição Conselho

- adesao/views.py
- gestao/templates/detalhe_municipio.html
- snc/settings.py
- snc/templates/termos/minuta_acordo.html
Correção de Formatação e implementação de UF no termo!
> Fix termo minuta de acordo

- snc/templates/termos/minuta_acordo.html
> [UPDATE] Ajuste de formatação

- adesao/urls.py
- adesao/views.py
- snc/templates/base.html
- snc/templates/erro_impressao.html
os documentos do acordo de cooperação e termo de solicitação
Co-authored-by: Gabriel Cabral <cabraldealmeida@gmail.com>
> [ADD] Adicionando mensagem de dados não cadastrados ao tentar exportar

- adesao/utils.py
Co-authored-by: Gabriel Cabral <cabraldealmeida@gmail.com>
> [FIX] exportação de arquivos do plano de trabalho (Fundo e Conselho)

- adesao/templates/cadastrar_funcionario.html
- adesao/templates/formulario_sistema.html
- snc/templates/base.html
> [Fix] correção de formulario  com asteristico

- snc/templates/termos/minuta_acordo.html
> [fix]  correção do acordo para versão 2020

- adesao/templates/frm_cadastro_sistema.html
Pull request para subir para o ambiente de HMG
> adicionando nova api para validar e colher os dados do cnpj

- planotrabalho/forms.py
- snc/templates/planotrabalho/cadastrar_conselho.html
- snc/templates/planotrabalho/cadastrar_plano.html
V. Plano de Cultura:
nos campos Indique o ano de início do curso, Indique o ano de término do curso:
✓permitir que inicio e fim sejam o mesmo ano
✓colocar máscara de quatro dígitos pra ano
✓Ano de término não pode ser menor que o de início
Conselho de Política Cultural:
no input 2.2 Instalação do Conselho de Política Cultural
Data de publicação da lei do Conselho de Política Cultural:
✓a data não poder ser futura
no input Data de Assinatura da Ata da última reunião:
✓a data não poder ser futura
> Pequenas correções 

- planotrabalho/forms.py
- snc/templates/base.html
… em Órgão gestor e Fundo de Cultura
> Adiciona máscara de conta corrente

- planotrabalho/forms.py
… Lei de Criação do Sistema de Cultura, seja maior que a de hoje
> Impedir data futura em Lei do sistema de cultura

- planotrabalho/forms.py
Reverts culturagovbr/sistema-nacional-cultura#844
> Revert "altera agência e conta para não serem obrigatórios"

- gestao/views.py
- planotrabalho/forms.py
- snc/templates/gestao/inserir_documentos/inserir_fundo_cultura.html
Corrige bug que exigia o gestor concordar com os termos de responsabilidade;
adiciona banco, agencia e conta na view do gestor de fundo de cultura
> Modificações em gestao

- planotrabalho/forms.py
Corrige bug que impede salvar Conselho de Política Cultural quando ata está como "não"
> Corrige Bug Conselho de Política Cultural

- adesao/migrations/0053_auto_20200211_1908.py
Reverts culturagovbr/sistema-nacional-cultura#830
> Revert "Alteração arquivo 0053_auto_20200211_1908.py"

- adesao/forms.py
- adesao/models.py
- adesao/templates/troca_cadastrador.html
- adesao/urls.py
- adesao/views.py
- snc/templates/base.html
Reverts culturagovbr/sistema-nacional-cultura#868
> Revert "Ente federado"

- adesao/urls.py
- adesao/views.py
Reverts culturagovbr/sistema-nacional-cultura#877
> Revert "adesao"

- snc/templates/base.html
Reverts culturagovbr/sistema-nacional-cultura#876
> Revert "altera base"

- adesao/forms.py
- adesao/migrations/0053_auto_20200211_1908.py
- adesao/templates/troca_cadastrador.html
- adesao/urls.py
- adesao/views.py
- gestao/views/views.py
Reverts culturagovbr/sistema-nacional-cultura#875
> Revert "ente federado adesao"

- adesao/views.py
- gestao/templates/detalhe_solicitacao_cadastrador.html
- gestao/urls/urls.py
- gestao/views/views.py
junção da base que o luiz fez o fork para uma branch que soma o que foi feito sem "matar" as outras atualizações
> ajustes da branch do luiz

- snc/templates/termos/minuta_acordo.html
Reverts culturagovbr/sistema-nacional-cultura#904
> Revert "Correção espaçamento paragrafos 5,10,15 e Solcitação"

- gestao/forms.py
Reverts culturagovbr/sistema-nacional-cultura#952
> Revert "Alteraçao do tipo de componente na operaçao save da classe Diligencia…"
