culturagovbr/sistema-nacional-cultura

requirements.txt

Força a versão 1.1.1 do django-smart-selects instalada via URL e também o drf-hal-json via git.

[UPDATE] Atualiza o requirements.txt

---

api/filters.py
api/pagination.py
api/serializers.py
api/urls.py
api/views.py

Substituição de alguns comentários por docstrings e organização das importações de acordo com a seguinte ordenação:
- Componentes distribuídos por padrão pelo Python (os, sys, ...)
- Componentes padrão do Django (django.shortcuts, django.db, ...)
- Componentes externos ao Django (rest_framework, django_hosts, ...)
- Componentes do próprio projeto, mas externos à aplicação (ex: planogestao.models)
- E por fim, os componentes próprios da aplicação em questão (ex: .models, .filters, ...)

[FIX] Reorganização de código - comentários e imports

---

snc/templates/gestao/detalhe_municipio.html

Corrige problema de aparecer o título **Município** tanto para um ente federado estadual quanto para o municipal.

[FIX] Corrige título para município e estado na tela de gestao

---

adesao/tests.py
adesao/views.py
env.tmpl
snc/settings.py

Mediante demanda da área negocial, era necessário o envio de um e-mail aos administradores competentes assim que uma nova adesão fosse solicitada.
Para isso fora adicionado um novo método que é acionado assim que uma nova adesão é solicitada.
O método, basicamente, envia um e-mail aos administradores contendo as informações necessárias para que o contato entre as partes seja facilitado.

Issue #82 - Notificação de Nova Adesão

---

api/serializers.py
api/static/swagger/swagger.json
api/tests.py
api/urls.py
requirements.txt
snc/hosts.py
snc/settings.py
snc/templates/swagger/index.html
snc/urls.py

Urls da api agora não se encontram mais no subdomíno "api.". Formato das novas urls:
- /api - Swagger 
- /api/v1/"endpoints" - Acessa os endpoints especificados

Retira dependência do django_hosts e corrige urls

---

snc/settings.py

As configurações do Raven esperavam uma string, quando deveriam esperar um booleano.

[HOTFIX] Altera a configuração do Raven.

---

api/filters.py
api/serializers.py
api/tests.py

- Retorna campo ```data_adesao``` para o endpoint ```sistemadeculturalocal/```
- Filtra entes federados(```sistemadeculturalocal/```) por data de adesão através dos parâmetros:
- ```data_adesao``` - Recebe uma data no formato YYYY-MM-DD, e retorna entes federados com a data de adesão igual a passada pela parâmetro
- ```data_adesao_min``` - Recebe uma data no formato YYYY-MM-DD, e retorna entes federados com a data de adesão maior ou igual a passada como parâmetro.
- ```data_adesao_max``` - Recebe uma data no formato YYYY-MM-DD, e retorna entes federados com a data de adesão menor ou igual a passada como parâmetro.
- Ao combinar os dois parâmetros acima é possível retornar os entes federados com a data de adesão com o valor entre os passados pelos parâmetros.

Inclui campo data de adesão e filtro por data

---

.github/ISSUE_TEMPLATE.md

Adiciona Issue template para padronizar a criação de issues. O PR foi feito para master pois o github só atualiza o template se estiver na master.

Adiciona issue template

---

adesao/models.py
adesao/tests/test_models.py

Altera o metodo save da model SistemaCultura para que qualquer modificação a uma determinada instancia gere uma nova instancia ao invés de modificar a atual. Assim, é possível manter um histórico de cada alteração ocorrida a um sistema de cultura.

Modifica o metodo save de SistemaCultura

---

api/filters.py
api/tests.py

Adiciona o lookup_expr 'iexact' no filter de sigla do estado e nome do município a fim de tornar a busca case insensitive, conforme issue #163.

Fix case sensitive

---

snc/settings.py

Abre a API para receber requisições de qualquer origem.
Necessário para o VerSNC.

[UPDATE] Permite qualquer origem de requisição para a API

---

adesao/models.py
adesao/tests/test_models.py

Implementa filtro por UF e Cidade de ao retornar um `SistemaCultura` ativo. Sem essa filtragem não seria possível retornar o sistema cultura ativo de um ente federado específico.
- Issue #188

[UPDATE] Filtra sistema cultura ativo por uf e cidade

---

gestao/tests/test_views.py
gestao/views.py

Ordena entes federados, na tela de gestão, dos mais antigos para os mais novos, sendo que os ainda não analisados tem prioridade, assim como os já publicados no DOU, conforme #143

Issue 143 filtrar por data

---

api/filters.py
api/tests/test_api.py

Adiciona filtragem de sistemas de cultura locais(`/sistemadeculturalocal`) por situação dos componentes do plano de trabalho dos entes federados, através dos parâmetros:
- Pelo ID da situação:
- `?situacao_lei_id`
- `?situacao_orgao_id`
- `?situacao_fundo_id`
- `?situacao_plano_id`
- `?situacao_conselho_id`
- Pela descrição da situação:
- `?situacao_lei_descricao`
- `?situacao_orgao_descricao`
- `?situacao_fundo_descricao`
- `?situacao_plano_descricao`
- `?situacao_conselho_descricao`
Corrigido também os campos utilizados para filtrar situação.

Filtrar por situação dos componentes no sistema de cultura local

---

gestao/templates/detalhe_municipio.html
gestao/tests/test_views.py
snc/templates/consultar/detalhar.html

- Corrige acesso ao atributo plano, no link para download 
- Corrige acesso à situação do plano, na tela de consulta de informações do ente
- Adiciona testes que verificam se os links para download foram gerados corretamente para cada componente
Closes #376 #375

Corrige link para download dos planos de cultura

---

adesao/templates/cadastrar_sistema.html

No módulo de adesão, na alteração do ente federado, o template não tinha o field 'ente_federado' e por isso ía para o changed_data, mas não para o cleaned_data, dando erro quando o form tentava acessá-lo no cleaned_data.
O commit coloca o field com o objeto já setado no template para que exista o valor pro field ente_federado.

Adiciona field com ente já setado na alteração

---

adesao/templates/templated_email/adesao.email
adesao/tests/test_views.py
adesao/urls.py
adesao/views.py
snc/templates/consultar/consultar.html

Como a view Detalhar usava o id do sistemacultura como pk, os links para os entes federados ficavam mudando, uma vez que é gerado um novo sistemacultura quando este é alterado, portanto, a view foi alterado para buscar o objeto a ser detalhado pelo código IBGE do ente federado, que é único.

Altera a view Detalhar pra usar cod_ibge

---

adesao/forms.py
adesao/tests/test_forms.py

Por algum motivo, existe mais de uma instância de User com o mesmo email. Como na validação é feito um get(), ocorre o erro da issue #461, dessa forma, o get() foi substituído por um filter, checando então se ele é ou não vazio.

Altera clean_email da criação de usuário para utilizar filter

---

gestao/forms.py
gestao/tests/test_views.py

Antigamente era necessário remover a data de publicação no DOU do ente quando se alterava o cadastrador, como essa regra de negócio não é mais válida, isto foi removido do form e foi removido o teste que checava isso.

Remove regra de negócio obsoleta na alteração de cadastrador

---

snc/templates/planotrabalho/cadastrar_conselho.html

No Menu Principal > Plano de Trabalho, o campo Data de Publicação da Lei do Conselho de Cultura estava sem máscara.

adiciona mascara de data para o field data_publicacao_lei

---

planotrabalho/forms.py
snc/templates/planotrabalho/cadastrar_fundo.html

Corrige bug que exigia agência e conta mesmo o usuário selecionando 'não' para o field O Fundo de Cultura possui CNPJ?;
altera texto 'O Fundo de Cultura possui ?' para 'O Fundo de Cultura possui CNPJ?'

Lei de criação do Fundo de Cultura: agencia e conta
